### ISSUE TITLE
看了你的Ijkplayer,能否给个demo参考下呢?

### ISSUE THREAD

**Issue by yhnu** [geron-cn/geron-cn.github.io#1]
immb@qq.com
happyyi

**Comment by geron-cn** [comment]
不好意思，现在才看到消息， 
https://pan.baidu.com/s/1giqzQ7fC8vcPqtps4Hs1jQ nm79 这个是链接


发自我的 iPhone

**Comment by yhnu** [comment]
获益匪浅,非常感谢
